### ISSUE TITLE
Out of box, :fabric:build fails, when gradle is run with Java 25

### ISSUE THREAD

**Issue by SubordinalBlue** [JT122406/ArchLoom-Multiloader-Template#3]
`./gradlew :fabric:build` results in:

```
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:transformProductionFabric'.
> Failed to remap /{elided}/ArchLoom-Multiloader-Template/common/build/devlibs/ExampleMod-common-1.0-dev.jar to /{elided}/ArchLoom-Multiloader-Template/common/build/libs/ExampleMod-common-1.0-transformProductionFabric.jar
```

Out of box, `:neoforge:build` and `:forge:build` targets are successful.

**Comment by SubordinalBlue** [comment]
Amendment:

:fabric:build fails, running cradle with Java25; the other two loader's build targets succeed.

**Comment by JT122406** [comment]
Which MC version are you targeting?

**Comment by SubordinalBlue** [comment]
1.21.1, as set in the repo; literally "out of box", no changes at all.

Just using java25 to run gradle causes this problem.

Came across it while working on moving a private repo generated from an earlier version of this template, and on a whim decided to check what happens with the latest version of this template.

**Comment by JT122406** [comment]
I would try now, I pushed a commit for newer loom and gradle which should support Java 25, lmk

**Comment by SubordinalBlue** [comment]
Thanks!

But... `./gradlew clean :fabric:build` still fails for me, same error.

As a sanity check, with `:neoforge:build` target, it (still) works.

**Comment by SubordinalBlue** [comment]
further info on my system and process:

```fish
❯ java --version
openjdk 25.0.1 2025-10-21
OpenJDK Runtime Environment Homebrew (build 25.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 25.0.1, mixed mode, sharing)
```

`git pull`ed, again, just before running the previously mentioned build command.

**Comment by SubordinalBlue** [comment]
whoops, wrong button, didn't mean to close the issue yet. (my bad)

**Comment by SubordinalBlue** [comment]
On the off-chance it was the fault of my installed-from-homebrew Java25, I've tried with Microsoft's OpenJDK 25.0.1 -> same result.

**Comment by JT122406** [comment]
Ok so I checked myself this seems to just be an issue with Loom that is supposed to be fixed in 1.14
